Onkar neww
hackkrmu/hackkrmu.github.io pull request #17
Opened 2022-12-17 03:32 UTC by onkar-01

solve all issue related to media queries

2022-12-22 16:29 UTC, sagar-7227 requested changes
Need changes in the team section and remove unnecessary faq's

2022-12-23 16:21 UTC, zeborg submitted a review, later dismissed

2022-12-23 16:32 UTC, zeborg requested changes

2022-12-23 16:32 UTC, zeborg commented on index.html
> +        </div>
Please don't make PR against `master` if the code is incomplete. Instead merge the changes to a new dev branch or resume working on the existing branch until the changes are final, and then make a PR against `master`.

2022-12-24 14:12 UTC, merged